version: '3'
services:
  ssl-portal:
    image: $IMAGE
    restart: always
    ports:
      - 8081:8080
      - 5000:5000
      - 8000:8000
    environment:
      - NODE_ENV=production
      - REACT_APP_AUTH0_DOMAIN=$REACT_APP_AUTH0_DOMAIN
      - REACT_APP_AUTH0_CLIENT_ID=$REACT_APP_AUTH0_CLIENT_ID
      - REACT_APP_AUTH0_DOMAIN=$REACT_APP_AUTH0_DOMAIN
