[build]
  command = "CI=false npm run build"
  publish="/build"
  base = "/webapp"
  
[[redirects]]
  from = "/*"
  to = "https://openslide-demo.s3.dualstack.us-east-1.amazonaws.com/:splat"
  status = 200
